sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run stephengrider/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "quasar-docker"
  env: "QuasarDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-567964750178"
  bucket_path: "quasar-docker"
  on:
    branch: master
  access_key_id: $ACCESS
  secret_access_key:
    secure: "$SECRET"

